### ISSUE TITLE
Site code filtering

### ISSUE THREAD

**Issue by plumpudding** [plumpudding/hopglass-server#14]
IP:4000/site-code/nodes.json or graph.json should return a filtered version
Later a universal filter

**Comment by anoymouserver** [comment]
Wouldn't it be better to use GET querys, so it is universal?
Otherwise you will have a problem when adding new filters for e.g. only online nodes.

e.g. `<address>:4000/nodes.json?filter=site&value=<site-code>`

**Comment by plumpudding** [comment]
Possible. But I will have to take a closer look at it. First I'm doing a small development break. 

On March 17, 2016 10:44:25 AM GMT+01:00, "anoy." <notifications@github.com> wrote:
>Wouldn't it be better to use GET querys, so it is universal?
>Otherwise you will have a problem when adding new filters for e.g. only
>online nodes.
>
>e.g. `<address>:4000/nodes.json?filter=site&value=<site-code>`
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/plumpudding/hopglass-server/issues/14#issuecomment-197791227

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anoymouserver** [comment]
I've made a minimal example, so you can see what I meant and how it could be implemented.

https://gist.github.com/anoymouserver/f7065bb205fc3f0761a006a27f3ed9ad

**Comment by anoymouserver** [comment]
see #30
