### ISSUE TITLE
graph.json is not populated

### ISSUE THREAD

**Issue by tantive** [plumpudding/hopglass-server#2]
curl 'http://192.168.1.74:4000/graph.json'
{"version":1,"batadv":{"multigraph":false,"directed":false,"nodes":[],"links":[],"graph":null},"timestamp":"2016-02-05T18:06:05.531Z"}

curl 'http://192.168.1.74:4000/metrics' | grep meshnodes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  451k    0  451k    0     0   619k      0 --:--:-- --:--:-- --:--:--  618k
meshnodes_total 768
meshnodes_online_total 724

**Comment by plumpudding** [comment]
Interesting..
I need more information on that..

**Comment by plumpudding** [comment]
I got it: the three categories have to be queried seperately.

**Comment by tantive** [comment]
works like a charm ;)
