### ISSUE TITLE
path to aliases.json is not a config option

### ISSUE THREAD

**Issue by mar-v-in** [plumpudding/hopglass-server#28]
I am not sure what's the current development branch as 0.1rc1 is not in master yet. There are huge differences in config file handling between master and 0.1rc1 so I was not sure, on which branch I should base a pull request. Do you consider master branch to be stable or development branch?

**Comment by plumpudding** [comment]
Master is stable,
PRs should go to modules
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anoymouserver** [comment]
I've already implemeted this at [anoymouserver/hopglass-server modules_dev](/anoymouserver/hopglass-server/tree/modules_dev) and it will be merged together soon.

**Comment by anoymouserver** [comment]
see #29
