### ISSUE TITLE
feature request: value firmware-version

### ISSUE THREAD

**Issue by eriu** [plumpudding/hopglass-server#34]
It will be great if the respond collector can collect the firmware version of a node.

**Comment by plumpudding** [comment]
It can. It just has to be processed correctly by the HopGlass Web Client.

On May 12, 2016 9:31:50 AM GMT+02:00, Michel <notifications@github.com> wrote:
>It will be great if the respond collector can collect the firmware
>version of a node.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/plumpudding/hopglass-server/issues/34

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eriu** [comment]
how i can visualize the firmware-data with grafana? :)

**Comment by plumpudding** [comment]
Aaah. That's a different story..
I'll write more later.

On May 12, 2016 10:54:07 AM GMT+02:00, Michel <notifications@github.com> wrote:
>how i can visualize the firmware-data with grafana? :)
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/plumpudding/hopglass-server/issues/34#issuecomment-218698086

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by plumpudding** [comment]
"later"
much later

Firmware data is easy to monitor, because it consists of strings instead of floats. Prometheus can only have float values. What I can and will do is include the firmware version as a label. It's just not as fancy.

**Comment by plumpudding** [comment]
done.
use something like `count(online) by (firmware)`
